### ISSUE TITLE
Move notebooks to lightning-tutorials

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning-flash#10]
## 🚀 Feature

better and faster testing of attached notebooks

### Additional context

https://blog.kovalevskyi.com/continues-integration-for-your-jupyter-notebooks-on-github-with-gcp-f72af5b08bcd

**Comment by edgarriba** [comment]
What do you test here, success or previous cached results ?

**Comment by Borda** [comment]
> What do you test here, success or previous cached results ?

we shall test the execution...

**Comment by edgarriba** [comment]
In kornia I'm using https://myst-nb.readthedocs.io that runs every time the notebook every time we build docs

**Comment by akihironitta** [comment]
As another option, we could use `--nbval` which is an extension of pytest to test notebook cells. https://github.com/computationalmodelling/nbval

**Comment by Borda** [comment]
> As another option, we could use `--nbval` which is an extension of pytest to test notebook cells. https://github.com/computationalmodelling/nbval

Very nice, is it something new?

**Comment by akihironitta** [comment]
Seems It has existed for years like since around 2015 :]

**Comment by Borda** [comment]
@ethanwharris let's move all notebooks here: https://github.com/PyTorchLightning/lightning-tutorials
