### ISSUE TITLE
Flash serve on Object Detection task

### ISSUE THREAD

**Issue by ethanwharris** [Lightning-AI/lightning-flash#1279]
### Discussed in https://github.com/PyTorchLightning/lightning-flash/discussions/1277

<div type='discussions-op-text'>

<sup>Originally posted by **IncubatorShokuhou** April  7, 2022</sup>
Is there an exampe on serving an object detection model in lightning-flash?</div>

**Comment by MrBlenny** [comment]
I would also be interested in this... Currently I'm using an awful hack where I write images (received as bas64) to disk and then read them using `ObjectDetectionData.from_files` https://github.com/Greenroom-Robotics/nuclio_lighting_flash/blob/main/nuclio_lighting_flash/flash_model_handler.py#L27

In addition to the `model.serve` it would be nice to have something like `ObjectDetectionData.from_image` which accepted pil images.
