### ISSUE TITLE
Load COCO dataset error

### ISSUE THREAD

**Issue by morestart** [Lightning-AI/lightning-flash#1303]
```
AUTOFIX-FAIL - (record_id: 200365) - Cannot auto-fix coordinates: <BBox (xmin:296.65, ymin:388.33, xmax:297.67999999999995, ymax:388.33)>
	y_min:388.33 is greater than or equal to y_max:388.33 | icevision.utils.logger_utils:autofix_log:17
AUTOFIX-REPORT - (record_id: 200365) Removed annotation with index: 2, for more info check the AUTOFIX-FAIL messages above | icevision.core.record:autofix:45

NotImplementedError: _remove_annotation does not work for mask component, if you're getting this on autofix, it's probably means this record has to be fixes manually

```

this is my code:

```python

from flash.image import InstanceSegmentationData

datamodule = InstanceSegmentationData.from_coco(
    train_folder='/home/jp/Documents/COCO/train2017',
    val_folder='/home/jp/Documents/COCO/val2017',
    train_ann_file='/home/jp/Documents/COCO/annotations/instances_train2017.json',
    val_ann_file='/home/jp/Documents/COCO/annotations/instances_val2017.json',
    batch_size=128,
)
```

**Comment by ethanwharris** [comment]
Hey @morestart thanks for reporting this! This error happens because one of the annotations is invalid (in this case the mask has zero width as y_min == y_max) and there's no way for it to be automatically fixed. Are you able to edit the annotation for that record to fix it?

One option for us to fix this on our end is to try to catch the error and just drop the corrupted record from the data, although I'm not sure it's desireable for us to quietly drop some data. Let me know what you think 😃

**Comment by morestart** [comment]
I think we should del the invalid mask

**Comment by krshrimali** [comment]
I'm not confident if it's a good idea to drop annotations that are invalid. That would be unsafe.

@morestart - just curious, is this the original COCO dataset?

**Comment by morestart** [comment]
@krshrimali thanks for you reply! This is the raw data and annotation. Why is unsafe？ i think we can remove it from memory. just have a chcke when we use it

**Comment by krshrimali** [comment]
> @krshrimali thanks for you reply! This is the raw data and annotation. Why is unsafe？ i think we can remove it from memory. just have a chcke when we use it

Well, I'm happy to be wrong here, but I personally would not expect a library to clean my dataset unless and until a flag is set. Maybe, we can have a flag that when set `True` removes it from memory?

**Comment by krshrimali** [comment]
But yes, just to iterate - this can/should be resolved in some way. Just thinking about what can be the best solution here. :)

**Comment by morestart** [comment]
yes, maybe set a flag is a good idea for that. but if we set flag==False, the program will break by this error. so... if we want our program run well, wo must set flag==True.

**Comment by morestart** [comment]
yes, maybe set a flag is a good idea for that. but if we set flag==False, the program will break by this error. so... if we want our program run well, wo must set flag==True.
