### ISSUE TITLE
SemanticSegmentationFilesInput does not accept .npy files

### ISSUE THREAD

**Issue by chris-clem** [Lightning-AI/lightning-flash#1308]
## 🐛 Bug

It seems that `SemanticSegmentationFilesInput` does not accept `.npy` files.

```python
class SemanticSegmentationFilesInput(SemanticSegmentationInput):
    def load_data(
        self,
        files: Union[PATH_TYPE, List[PATH_TYPE]],
        mask_files: Optional[Union[PATH_TYPE, List[PATH_TYPE]]] = None,
        num_classes: Optional[int] = None,
        labels_map: Optional[Dict[int, Tuple[int, int, int]]] = None,
    ) -> List[Dict[str, Any]]:
        self.load_labels_map(num_classes, labels_map)
        if mask_files is None:
            files = filter_valid_files(files, valid_extensions=IMG_EXTENSIONS)
        else:
            files, mask_files = filter_valid_files(files, mask_files, valid_extensions=IMG_EXTENSIONS)
        return to_samples(files, mask_files)
```

`files, mask_files = filter_valid_files(files, mask_files, valid_extensions=IMG_EXTENSIONS)` 
should be 
`files, mask_files = filter_valid_files(files, mask_files, valid_extensions=IMG_EXTENSIONS + NP_EXTENSIONS)` ?

**Comment by krshrimali** [comment]
Hi, @chris-clem - Thank you for creating this issue! Could you please share a sample `npy` file with us? I would love to consider this if it's not supported already!

Also, yes, I agree that they should be supported. Maybe we just didn't have anyone demanding this, so we went with the image extensions initially. :)

**Comment by Borda** [comment]
@chris-clem mind sending a quick PR?
