### ISSUE TITLE
allow sizing for show sample batch

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning-flash#1314]
### Motivation

just found that Flash has a magic function show sample batch which replaces this boilerplate I had in past
```py
fig, axarr = plt.subplots(ncols=2, nrows=5, figsize=(10, 25))
for batch in datamodule.val_dataloader():
    print(batch.keys())
    for i in range(5):
        segm = batch['target'][i].numpy()
        img = np.rollaxis(batch['input'][i].cpu().numpy(), 0, 3)
        axarr[running_i, 0].imshow(img)
        axarr[running_i, 1].imshow(segm)
    break
```

but the size is to small so would be nice to allow set fig size or limit nb samples in given batch
![image](https://user-images.githubusercontent.com/6035284/165700301-a3b7b99c-f320-41d5-a7ac-928d4d3dc5b8.png)

### Pitch

Increase the flexibility of visualization

### Additional context

running Flash in real applications :P

**Comment by MrShevan** [comment]
Hi, looks interesting :) can I get it?

**Comment by Nico995** [comment]
Hi, I would love to work on this as my contribution! Can I give it a try?

**Comment by krshrimali** [comment]
Hi, @Nico995 - Thank you for your interest! I've assigned you to this issue, please go ahead, looking forward to a PR. If you get stuck somewhere, please create a draft PR and let us know. Happy to help from there. :)
