### ISSUE TITLE
Docs for using `output` with `ObjectDetector`

### ISSUE THREAD

**Issue by eric-tc** [Lightning-AI/lightning-flash#1344]
## 🐛 Bug

I'am trying to use FiftyOneDetectionLabelsOutput output for Object detection but i got the following error

model = model_type.model(backbone=backbone, num_classes=num_classes, **kwargs)
TypeError: model() got an unexpected keyword argument 'output'

How can i correctly setup the output?

### To Reproduce
from flash.image.detection.output import FiftyOneDetectionLabelsOutput
from flash.image import ObjectDetector

out= FiftyOneDetectionLabelsOutput(threshold=0.7)
objDetc=ObjectDetector(num_classes=81,backbone="medium",head="yolov5",output=out)

### Expected behavior
Class init correctly as described in documentation

https://lightning-flash.readthedocs.io/en/latest/api/generated/flash.image.detection.model.ObjectDetector.html#flash.image.detection.model.ObjectDetector
There is a parameter output in the description. Maybe is an old value

### Environment

 - OS (e.g., Linux): Linux
 - Python version: 3.8
 - PyTorch/Lightning/Flash Version (e.g., 1.10/1.5/0.7): 1.10 / 1.5.8 / 0.7.4
 - GPU models and configuration: cuda 11.3

**Comment by ethanwharris** [comment]
Ah, thanks @eric-tc, looks like it just needs to be removed from the docstring here: https://github.com/PyTorchLightning/lightning-flash/blob/61e1a2d3b72f8fbbffe6ace14fb5b5bb35c5f131/flash/image/detection/model.py#L36

@eric-tc would you be interested in making a PR to contribute the fix?

**Comment by eric-tc** [comment]
Hi @ethanwharris,

yes I am interested. How I need to do the PR?  I need to follow this guidelines https://github.com/PyTorchLightning/lightning-flash/blob/master/.github/CONTRIBUTING.md Thanks
