### ISSUE TITLE
Unsafe MongoClient forks when creating datamodule from FiftyOne

### ISSUE THREAD

**Issue by iamkucuk** [Lightning-AI/lightning-flash#1348]
## 🐛 Bug

MongoDB shows a warning message when I try to add additional workers. The message is: `/opt/conda/lib/python3.8/site-packages/pymongo/topology.py:164: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe`

### To Reproduce

Create any datamodule like this

```
datamodule = SemanticSegmentationData.from_fiftyone(
    train_dataset = dataset.match_tags('train'),
    val_dataset = dataset.match_tags('val'),
    predict_dataset= dataset.match_tags('val'),
    transform_kwargs=dict(image_size=(1024, 1024)),
    batch_size=8,
    num_workers=8,
    label_field='ground_truth',
    num_classes=3
)
```
The given warning message is:

`/opt/conda/lib/python3.8/site-packages/pymongo/topology.py:164: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe`

Please note that there are no problems with default value of the `num_workers`  parameter.

#### Code sample
Create a fiftyone dataset like:
```
dataset = fo.load_dataset('carla')
```

and create a lightning datamodule by:

```
datamodule = SemanticSegmentationData.from_fiftyone(
    train_dataset = dataset.match_tags('train'),
    batch_size=4,
    num_workers=4,
    num_classes=21
)
```

### Expected behavior

No warning message.

### Environment

 - OS (e.g., Linux): Ubuntu 20.04
 - Python version: 3.8.12
 - PyTorch/Lightning/Flash Version (e.g., 1.10/1.5/0.7): 1.11.0/1.6.3/0.7.5
 - GPU models and configuration: RTX3090, single node/single gpu
 - Any other relevant information: fiftyone version: 0.15.1, mongoengine version: 0.20.0

### Additional context

There are no problems with default value of the `num_workers`  parameter. (which is 0)

**Comment by ethanwharris** [comment]
Hey @iamkucuk thanks for reporting this! I think unfortunately there's nothing we can do on the Flash side to resolve this as I believe it will happen any time fiftyone is imported and the process gets forked (which happens with multiple workers). I'll close this one but consider opening an issue in the fiftyone repo where they may be able to help you further / advise if the warning can be safely ignored. Thanks! 😃
