### ISSUE TITLE
Bug with Tabular examples

### ISSUE THREAD

**Issue by raiv-toulouse** [Lightning-AI/lightning-flash#1363]
## 🐛 Bug

I try the [Tabular classification example](https://github.com/PyTorchLightning/lightning-flash/blob/0.5.2/flash_examples/tabular_classification.py) and the [Tabular regression example](https://github.com/PyTorchLightning/lightning-flash/blob/0.5.2/flash_examples/tabular_regression.py) and both produce the same error  : 
 
`
  File "/home/phil/Envs/science/lib/python3.8/site-packages/omegaconf/nodes.py", line 272, in _validate_and_convert_impl
    raise ValidationError(

omegaconf.errors.ValidationError: Value '(5, 16)' of type 'tuple' could not be converted to Integer

    full_key: embedding_dims[0]

    reference_type=Optional[List[int]]

    object_type=list
`

### Environment

 - OS (e.g., Linux): Ubuntu 20.04
 - Python version: 3.8.10
 - PyTorch/Lightning/Flash Version (e.g., 1.10/1.5/0.7): 1.6.4 / 0.7.5
 - GPU models and configuration:
 - Any other relevant information:

**Comment by krshrimali** [comment]
Hi, @raiv-toulouse - Thank you for raising this issue. I believe this has to do something with omegaconf's version, we recently fixed this here: https://github.com/Lightning-AI/lightning-flash/pull/1346. It had to do with omegaconf's recent changes, can you please try installing omegaconf 2.1.1 using: `pip --force-reinstall omegaconf==2.1.1` and see if that fixes the issue for you?
