### ISSUE TITLE
Error message when `filter_valid_files` finds invalid files.

### ISSUE THREAD

**Issue by ethanwharris** [Lightning-AI/lightning-flash#1374]
Currently if you have invalid files they are silently dropped. If all are dropped then this will trigger a cryptic error. Instead we should give a good error message like:
```
Found invalid files: ..., ..., ..... The supported file extensions are: ...
```

**Comment by JustinGoheen** [comment]
I'd like to be assigned to this, please.

**Comment by ethanwharris** [comment]
Hey @JustinGoheen thanks for offering to work on this! I'll assign you to the issue 😃 The offending function can be found here: https://github.com/Lightning-AI/lightning-flash/blob/9c6fa13e1bc7fd9879ae5aa37d364c2a4df1c63f/flash/core/data/utilities/paths.py#L136

Let us know if you have any questions!

**Comment by JustinGoheen** [comment]
@ethanwharris do you mind if I incorporate [rich](https://rich.readthedocs.io/en/stable/introduction.html).

I've done something similar in a [personal project](https://github.com/JustinGoheen/lightning-pod/blob/475b292928f87eadd0be6026ccbbcbf7f8473cc2/lightning_pod/cli/console.py#L18)
![image](https://user-images.githubusercontent.com/26209687/178286337-837bb3cb-7178-4fd6-ba0f-0c82d88d4088.png)

The above isn't an error message; but I'd like to use Rich for formatting the basic message output, and potentially a table - if that isn't too verbose of a message.
