### ISSUE TITLE
Raise clearer error when module not available

### ISSUE THREAD

**Issue by krshrimali** [Lightning-AI/lightning-flash#1422]
Context:

> Hi, @jayqi - Thank you for the question. In terms of providing a more clear error, this hasn't been fixed. I'll re-open this issue, and I think a refactor will be good in Flash to add better errors if the module is not found. In case you are interested to pick this up, please feel free (also let me know so that I can assign you the issue). Else, I'll try to scope this for the next week, and create an issue and a PR around this. 🎉

cc: @ethanwharris - What do you think about the refactor to raise errors instead of running into: `NameError "T" not defined``.

Hint: https://github.com/Lightning-AI/lightning-flash/issues/1403#issuecomment-1219792770

_Originally posted by @krshrimali in https://github.com/Lightning-AI/lightning-flash/issues/1403#issuecomment-1219780935_

**Comment by krshrimali** [comment]
To the contributors: if anyone wants to pick it up, this is open to be taken by this weekend. If not, since this needs to be fixed - I'll attempt to pick it up and try finishing it by the next week. Feel free to let me know here if anyone is interested. 🔥 ⚡

**Comment by aniketmaurya** [comment]
hey @krshrimali, I would like to pick this up 😄

**Comment by krshrimali** [comment]
> hey @krshrimali, I would like to pick this up 😄 

Awesome, thanks @aniketmaurya! Assigning this to you, please reach out in case you need any help. Appreciate the help! 🔥
