### ISSUE TITLE
NameError: name 'K' is not defined

### ISSUE THREAD

**Issue by lcoandrade** [Lightning-AI/lightning-flash#1423]
## 🐛 Bug

Open a Colab notebook and try to perform a image segmentation by instantiating a SemanticSegmentationData using from_folders method.

This raises a NameError.

datamodule = SemanticSegmentationData.from_folders(
    train_folder=x_train_dir,
    train_target_folder=y_train_dir,
    val_folder=x_valid_dir,
    val_target_folder=y_valid_dir,
    test_folder=x_test_dir,
    test_target_folder=y_test_dir,
    transform_kwargs=dict(image_size=(256, 256)),
    num_classes=1,
    batch_size=16,
)

Error raised:

/usr/local/lib/python3.7/dist-packages/flash/image/segmentation/input_transform.py in train_per_sample_transform(self)
 49             [DataKeys.INPUT, DataKeys.TARGET],
 50             KorniaParallelTransforms(
---> 51                 K.geometry.Resize(self.image_size, interpolation="nearest"), K.augmentation.RandomHorizontalFlip(p=0.5)
 52             ),
 53         )
NameError: name 'K' is not defined

Instantiate the SemanticSegmentationData without raising any errors.

### Environment

 - Google Colab
 - Flash Version 0.7:

**Comment by krshrimali** [comment]
Hi, @lcoandrade - Thank you for raising this issue. We are working on making these errors clearer, but for now, could you please try installing `kornia`: `pip install kornia`, and try running the script again?

**Comment by krshrimali** [comment]
Hey, @aniketmaurya - Pinging you here (just so to verify that this issue is also fixed along with #1422), since you are fixing #1422 - and I think this issue will be resolved once #1422 is resolved. Hope that sounds good to you!

**Comment by lcoandrade** [comment]
Hi, @krshrimali. Thanks for your help. I've tried to install and import kornia as K to solve the problem, but what a really needed was just install it. Thanks again.
