### ISSUE TITLE
TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

### ISSUE THREAD

**Issue by DrRaja** [Lightning-AI/lightning-flash#1429]
Hi,
While trying to finetune a bert-base model for multi-label text classification, I keep encountering this error. TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]. I looked around and saw people suggesting to check if there's some missing values of None values in the dataset. I've checked my dataset and its been properly preprocessed to remove an NaN and missing values. I even compared my dataset with the toy example's dataset of toxic comments, and the only difference I could see was the number of categories (in my case these are > 30).

Can anyone please help me on this one?

Thank you

**Comment by uakarsh** [comment]
Hi @DrRaja, can you help in reproducing the error?

**Comment by DrRaja** [comment]
Here's my code:
`import torch

import flash
from flash.core.data.utils import download_data
from flash.text import TextClassificationData, TextClassifier

# 1. Create the DataModule

datamodule = TextClassificationData.from_csv(
    "answer_text",
    label_cols,
    train_file="/content/new-train.csv",
    batch_size=128,
    val_split=0.1
)

# 2. Build the task
model = TextClassifier(
    num_classes = datamodule.num_classes,
    backbone="bert-base-uncased",
    multi_label=True,
    # metrics=F1(num_classes=datamodule.num_classes)
    
)

# 3. Create the trainer and finetune the model
# model = TextClassifier(num_classes=datamodule.num_classes, backbone="prajjwal1/bert-tiny")
trainer = flash.Trainer(max_epochs=1)
trainer.fit(model, datamodule=datamodule)`

The 1st Epoch runs till 73% and then I get an error. This is the stack trace:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-63e6720f4bf3> in <module>
     28 # model = TextClassifier(num_classes=datamodule.num_classes, backbone="prajjwal1/bert-tiny")
     29 trainer = flash.Trainer(max_epochs=1)
---> 30 trainer.fit(model, datamodule=datamodule)

25 frames
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_fast.py in _batch_encode_plus(self, batch_text_or_text_pairs, add_special_tokens, padding_strategy, truncation_strategy, max_length, stride, is_split_into_words, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose)
    427             batch_text_or_text_pairs,
    428             add_special_tokens=add_special_tokens,
--> 429             is_pretokenized=is_split_into_words,
    430         )
    431 

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]`

I've checked my dataset, it doesn't have any missing values or NULLs.

**Comment by uakarsh** [comment]
Thanks for mentioning the error. I found this [online](https://stackoverflow.com/questions/63517293/valueerror-textencodeinput-must-be-uniontextinputsequence-tupleinputsequence). Did you see this? I think that, maybe due to the `is_split_into_words` argument or `nonstring type` in the column, the error might have been occurring.

**Comment by DrRaja** [comment]
@uakarsh, thank you for the response. Yes I came across that link while I was searching for the solution, but I just didn't understand how/where can I set the token as I'm not directly importing the tokenizer. Can you please help me with that?

**Comment by uakarsh** [comment]
Sure, if possible can you provide me the dataset, so that i can run on colab and try to debug it?

Regards,
Akarsh

**Comment by krshrimali** [comment]
Great to hear, @DrRaja - thank you so much @uakarsh for the discussion and the help! Lovely to see the community stepping forward. ⚡ 🔥

**Comment by DrRaja** [comment]
Thanks for your responses guys, really appreciate it. 

Is it possible to change the confidence thresholds in the prediction functions?

**Comment by uakarsh** [comment]
When you run [this](https://colab.research.google.com/gist/uakarsh/251406879460715551a1b47dad3a3bc2/sample-nb.ipynb) notebook, you would get an output like:

`[[tensor([  3.0591,  -6.4909,   1.8139, -16.4584,   2.6716,  -8.2024]), tensor([  4.9536,  -3.4972,   6.0760, -16.4508,   3.2731,  -7.8231]), tensor([ -7.2569, -13.6809,  -8.6636, -13.1463, -10.7626, -12.5976])]]`

So, I think that there is some issue with the threshold if I am not wrong. Maybe @krshrimali can help us guide us about where to look for the threshold. I scrolled through the code, i.e of Flash and Lightning Trainer, but I tend to get a bit lost about how to go about it.

**Comment by krshrimali** [comment]
Hey, @uakarsh and @DrRaja - I'm sorry for the delay. Please allow me a couple of days to get back to you on this. We are working on v0.8 release, hence the delay in response. I'll have to check the context to be able to get back, hopefully this weekend 🤞🏻! Thank you!

**Comment by ethanwharris** [comment]
Hey @uakarsh @DrRaja I think there you are just seeing the raw logits output from the model. To see e.g. probabilities you would need to use
```python
trainer.predict(model, datamodule=datamodule, output="probabilities")
```

To get classes or labels output with a custom threshold, you can pass the `Output` object yourself like this:
```
from flash.core.classification import LabelsOutput  # or ClassesOutput

trainer.predict(model, datamodule=datamodule, output=LabelsOutput(threshold=0.7))
```

Hope that helps :smiley:
