### ISSUE TITLE
resize instance segmentation mask

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning-flash#930]
## 🐛 Bug

found another paper-cut with instance segmentation...
it is not trivial/intuitive how to match mask with input image as output can be any size and mask is 128x128
so it is just scaled equally in each dimension is applied padding uniformly?

### To Reproduce

https://www.kaggle.com/jirkaborovec/cell-instance-segm-lightning-flash#Training-with-Flash-Lightning

**Comment by Borda** [comment]
from @ethanwharris:

> We have I think one task (semantic segmentation) where we resize the predictions to the original image size at the end. The way it works is the following:
> when the image is loaded we attach some metadata containing the original size of the image - here: https://github.com/PyTorchLightning/lightning-flash/blob/073166ebe805eca966ac05c86ff7fe5418f70fd1/flash/image/segmentation/data.py#L151
> the image is then resized or whatever and passed to the model and we get an output, but the metadata of the sample is preserved through the whole pipeline in the OutputTransform we resize the prediction back here: https://github.com/PyTorchLightning/lightning-flash/blob/073166ebe805eca966ac05c86ff7fe5418f70fd1/flash/image/segmentation/model.py#L43

**Comment by saurabhya** [comment]
hey! @Borda is this issue resolved? If not I would like to contribute to this.

**Comment by ethanwharris** [comment]
Hey @saurabhya I think this is still needed! Most of the above comment should still apply but let me know if you run into any issues and I'll be happy to go over it with you in more detail. Thanks :smiley:

**Comment by MrShevan** [comment]
Hi, @ethanwharrisis it still needed? May I take it? :) I researched all comments above and created Draft PR. 
It seems to solve this problem it is enough to add resize func to `OutputTransform` for Instance Segmentation Model, cause `IceVisionInput` already has logic for  attach some metadata containing the original size of the image.

**Comment by MrShevan** [comment]
Hi, I think my [PR](https://github.com/PyTorchLightning/lightning-flash/pull/1353) ready for review :) I added resize function and all necessary tests.
